server:
  port: 30001

# spring
spring:
  application:
    name: cloud-disks-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_cloud_disks_v100?characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
      map-underscore-to-camel-case: true  # 开启驼峰命名
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl