name: Build and Deploy UI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      # 版本管理
      PROJECT_NAME: 'cloud-disks-ui'
      PRO_VERSION: '1.0.0-SNAPSHOT'

      # 容器镜像
      ALIYUN_CR_REGISTORY: 'registry.cn-heyuan.aliyuncs.com'
      ALIYUN_CR_NAMESPACE: 'carrocean'

      SERVER_PORT: '80'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js for Vue
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.2'

      - name: Install Vue dependencies and build
        run: |
          cd cloud-disks-ui
          npm install
          npm run build
        env:
          CI: true

      - name: Build Docker images
        run: |
          cd cloud-disks-ui
          docker build -t ${{env.PROJECT_NAME}}:${{env.PRO_VERSION}} .

      - name: Login to Aliyun Container Registry
        run: |
          echo ${{ secrets.ALIYUN_REGISTRY_PASSWORD }} | docker login --username=${{ secrets.ALIYUN_REGISTRY_USER }} --password-stdin ${{ env.ALIYUN_CR_REGISTORY }}

      - name: Tag and push Vue image to Aliyun
        run: |
          docker tag ${{env.PROJECT_NAME}}:${{env.PRO_VERSION}} ${{ env.ALIYUN_CR_REGISTORY }}/${{env.ALIYUN_CR_NAMESPACE}}/${{env.PROJECT_NAME}}:${{env.PRO_VERSION}}
          docker push ${{ env.ALIYUN_CR_REGISTORY }}/${{env.ALIYUN_CR_NAMESPACE}}/${{env.PROJECT_NAME}}:${{env.PRO_VERSION}}

      - name: Deploy to Aliyun ECS
        run: |
          sshpass -p ${{ secrets.ALIYUN_ECS_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{secrets.ALIYUN_ECS_USER}}@${{secrets.ALIYUN_ECS_HOST}} << EOF
            docker pull ${{ env.ALIYUN_CR_REGISTORY }}/${{env.ALIYUN_CR_NAMESPACE}}/${{env.PROJECT_NAME}}:${{env.PRO_VERSION}}
            docker stop ${{env.PROJECT_NAME}} || true
            docker rm ${{env.PROJECT_NAME}} || true
            docker run --name ${{env.PROJECT_NAME}} -d -p ${{ env.SERVER_PORT }}:${{ env.SERVER_PORT }} ${{ env.ALIYUN_CR_REGISTORY }}/${{env.ALIYUN_CR_NAMESPACE}}/${{env.PROJECT_NAME}}:${{env.PRO_VERSION}}
          EOF